apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcobta-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bcobta
  template:
    metadata:
      labels:
        app: bcobta
    spec:
      containers:
      - name: bcobta
        image: dockerronaldrodriguez/bcobta:125
        ports:
        - containerPort: 5000
