name: Spring Boot APP CI CD to Kubernetes

on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test
      run: mvn -B test
  
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build App
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: /home/runner/work/bcobta/bcobta/target/bcobta-0.0.1-SNAPSHOT.jar
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: app-artifact
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        
