name: Spring Boot APP CI CD to Kubernetes
run-name: 'Build bcobta (build version: ${{github.run_number}})'
on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test
      run: mvn -B test
  
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build App
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: /home/runner/work/bcobta/bcobta/target/bcobta-0.0.1-SNAPSHOT.jar
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: app-artifact
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: /home/runner/work/bcobta/bcobta/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bcobta:${{github.run_number}}, ${{ secrets.DOCKERHUB_USERNAME }}/bcobta:${{github.run_number}}
    - name: Copiar k8s archivos
      run: |
        mkdir /tmp/k8s
        cp k8s/* /tmp/k8s
    - name: Alcanzar k8s repo
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.USERNAME_GITHUB }}/bcobta
        ref: main
        token: ${{secrets.my_pat}}
    - name: Copiar contenido 
      run: |
        mkdir -p bcobta
        cp /tmp/k8s/* bcobta
    - name: Actualizar manifiestos yml
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "image: ${{ vars.USERNAME_GITHUB }}/bcobta:.*"
        replace: "image: ${{ vars.USERNAME_GITHUB }}/bcobta:${{github.run_number}}"
        include: "bcobta/deployment.yml"
    - name: Actualizar yml en el repo
      run: |
        git config --global user.name ${{ vars.USERNAME_GITHUB }}
        git config --global user.email ${{ vars.EMAIL }}
        git remote set-url origin https://x-access-token:${{ secrets.my_pat }}@github.com/${{ vars.USERNAME_GITHUB }}/bcobta.git
        git add .
        git commit -am "Build ${{github.run_number}}"
        git push
