name: Spring Boot APP CI/CD to Kubernetes
run-name: 'Build bcobta (build version: ${{ github.run_number }})'
on:
  push:
    branches: ['master']

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test
      run: mvn -B test
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        repository: ${{ vars.USERNAME_GITHUB }}/bcobta
        ref: master
        token: ${{secrets.my_pat}}

      #- name: Find and Replace
      #  uses: jacobtomlinson/gha-find-replace@v3
      #  with:
      #    find: "image: ${{ secrets.DOCKERHUB_USERNAME }}/bcobta:.*"
      #    replace: "image: ${{ secrets.DOCKERHUB_USERNAME }}/bcobta:${{ github.run_number }}"
      #    include: "**deployment.yml"
      #    regex: true

      #- name: Validate deployment.yml changes
      #  run: |
      #    ls -R
      #    cat ./k8s/deployment.yml

      #- name: Push changes to repository
      #  uses: stefanzweifel/git-auto-commit-action@v4


