name: Spring Boot APP CI CD to Kubernetes

on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test
      run: mvn -B test
  
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build App
      run: ls -R
    #- name: Upload JAR
    #  uses: action/upload-artifact@v4
    #  with:
    #    name: artifact
    #    path: ./target/bcobta-0.0.1-SNAPSHOT.jar

    
